name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'src/**'
  workflow_dispatch:
    inputs:
      publish:
        description: Publish to NuGet
        default: None
        type: choice
        options:
          - 'No'
          - Staging
          - Production

jobs:
  build:
    env:
      BUILD_CONFIG: release
    name: Build
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v4
    
      - name: Set up .NET
        uses: actions/setup-dotnet@v4

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c ${{ env.BUILD_CONFIG }} --no-restore -p:ContinuousIntegrationBuild=true

      # - name: Test
      #   run: dotnet test -c ${{ env.BUILD_CONFIG }} --no-restore -p:ContinuousIntegrationBuild=true
    
      - name: Publish
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.publish != 'No'
        run: |
          dotnet pack -c ${{ env.BUILD_CONFIG }} --no-build
          dotnet nuget push build_output/packages/*.nupkg \
            -k ${{ github.event.inputs.publish == 'Staging' && secrets.NUGETTEST_API_KEY || secrets.NUGET_API_KEY }} \
            -s ${{ github.event.inputs.publish == 'Staging' && 'https://apiint.nugettest.org/v3/index.json' || 'https://api.nuget.org/v3/index.json' }}
